### ISSUE TITLE
Armar Script de Preguntas

### ISSUE THREAD

**Issue by andresbiso** [mily96/TP_Integrador_Tecnicas_avanzadas_programacion#22]
Armar un script sql que inserte las preguntas y sus respuestas en la BD

**Comment by mily96** [comment]
Ingresar 10 preguntas y respuestas de la siguiente pagina: chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/http://www.gob.gba.gov.ar/portal/portalgba/dppsv/cuestionario.pdf
